DATA CLEANING

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/Stray dog survey .csv")

In [3]:
df.head()

,Timestamp,Username,1. Your Name,2. Contact Number (Optional),3. Area / Locality Name,4. Your Pin code,5. Approximate number of stray dogs you see daily in your area,"6. Among the stray dogs you observe in your area, what is the approximate male-to-female ratio?",7. Have you noticed an increase in stray dog population over the past year?,8. Time when you see most stray dogs:,...,16. Are there open garbage dumps in your area?,17. Presence of water sources:,18. Do residents feed stray dogs?,19. Are there animal welfare volunteers/NGOs active in your area? (if yes then provide us with information),20. Have you seen sterilized dogs (ear-notched)?,21. Have you seen any injured dog in the past 6 months?,22. Rate the severity of the stray dog issue in your area:,23. Main concerns (select all that apply):,24. Has this issue affected your quality of life?,25. Any recommendations to solve this problem:
0,2026/02/12 5:28:36 PM GMT+5:30,ggcosmos708@gmail.com,Anant Saxena,NaN,Meston road,208001,6-10,About the same,Yes,Night,...,Yes,No,Yes,No,No,1-2,1.0,Nighttime barking,No,Addition of water and food sources for the dogs
1,2026/02/12 5:31:45 PM GMT+5:30,mahekagnihotri1113@gmail.com,Mahek,8.303198e+09,Govind nagar,208014,6-10,About the same,No,Evening,...,Yes,NaN,Yes,No,No,3-4,3.0,Nighttime barking;Aggressive behavior;Health/h...,No,There should be proper shelter homes for them
2,2026/02/12 5:34:12 PM GMT+5:30,tellanup@gmail.com,Anup Saxena,NaN,Meston Road,208001,15+,About the same,Yes,Night,...,Yes,Yes,Yes,No,No,3-4,3.0,Dog bites;Nighttime barking;Garbage scattering...,No,NaN
3,2026/02/12 5:34:12 PM GMT+5:30,yashgamer627@gmail.com,Priyanshu Tomar,7.408944e+09,"Subhash Road, Lal bunglow",208007,6-10,More males,Maybe,Morning,...,Yes,By Underground water pipelines,Yes,No,No,1-2,4.0,Aggressive behavior;Garbage scattering;Traffic...,No,Shelter for street dogs and proper vaccination...
4,2026/02/12 5:34:36 PM GMT+5:30,panirudh460@gmail.com,Aniket Pandey,7.007740e+09,"Shyam nagar,kanpur",208013,0-5,About the same,Yes,Evening,...,Yes,Yes,No,Yes,No,3-4,2.0,NaN,No,Make the small shelter for them and should be ...

In [6]:
df.columns

Index(['Timestamp', 'Username', '1. Your Name  ',
       '2. Contact Number (Optional)  ', ' 3. Area / Locality Name  ',
       ' 4. Your Pin code',
       '5. Approximate number of stray dogs you see daily in your area  ',
       '6. Among the stray dogs you observe in your area, what is the approximate male-to-female ratio? ',
       '7. Have you noticed an increase in stray dog population over the past year?  ',
       '8. Time when you see most stray dogs:   ',
       '9. Approximate number of puppy litters you've observed in the past 6 months: ',
       '10.  What typically happens to puppies in your area? (Select all that apply)',
       '11. Common behavior of strays in your area:   ',
       '12. Do dogs form packs in your area?   ',
       '13. Have you or anyone you know been bitten/chased by a stray dog?   ',
       '14. If yes, when did the last incident occur?   ',
       ' 15. Are there food outlets/restaurants nearby that attract dogs?  ',
       '16. Are there open garbage dumps in your area?   ',
       '17. Presence of water sources:  ',
       '18. Do residents feed stray dogs?   ',
       '19. Are there animal welfare volunteers/NGOs active in your area? (if yes then provide us with information)',
       '20. Have you seen sterilized dogs (ear-notched)?  ',
       '21.  Have you seen any injured dog in the past 6 months?   ',
       '22. Rate the severity of the stray dog issue in your area: ',
       '23. Main concerns (select all that apply):  ',
       '24. Has this issue affected your quality of life?   ',
       '25. Any recommendations to solve this problem:'],
      dtype='object')

Remove Unnecessary Columns

In [7]:
df = df.drop(columns=["Timestamp", "Email Address", "Name"], errors='ignore')

Check Missing Values

In [8]:
print(df.isnull().sum())

Username                                                                                                        0
1. Your Name                                                                                                    0
2. Contact Number (Optional)                                                                                   16
 3. Area / Locality Name                                                                                        0
 4. Your Pin code                                                                                               0
5. Approximate number of stray dogs you see daily in your area                                                  1
6. Among the stray dogs you observe in your area, what is the approximate male-to-female ratio?                 0
7. Have you noticed an increase in stray dog population over the past year?                                     0
8. Time when you see most stray dogs:                                                                           0
9. Approximate number of puppy litters you've observed in the past 6 months:                                    0
10.  What typically happens to puppies in your area? (Select all that apply)                                    0
11. Common behavior of strays in your area:                                                                     0
12. Do dogs form packs in your area?                                                                            1
13. Have you or anyone you know been bitten/chased by a stray dog?                                              0
14. If yes, when did the last incident occur?                                                                  24
 15. Are there food outlets/restaurants nearby that attract dogs?                                               0
16. Are there open garbage dumps in your area?                                                                  0
17. Presence of water sources:                                                                                 14
18. Do residents feed stray dogs?                                                                               2
19. Are there animal welfare volunteers/NGOs active in your area? (if yes then provide us with information)     1
20. Have you seen sterilized dogs (ear-notched)?                                                                1
21.  Have you seen any injured dog in the past 6 months?                                                        1
22. Rate the severity of the stray dog issue in your area:                                                      3
23. Main concerns (select all that apply):                                                                      5
24. Has this issue affected your quality of life?                                                               2
25. Any recommendations to solve this problem:                                                                 27
dtype: int64

In [9]:
df = df.fillna(method="ffill")

/tmp/ipykernel_136/567689999.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method="ffill")

Standardize Text Values

In [10]:
df = df.applymap(lambda x: x.lower() if isinstance(x, str) else x)

/tmp/ipykernel_136/181626504.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.lower() if isinstance(x, str) else x)

In [11]:
df.replace({
    "yes": 1,
    "no": 0
}, inplace=True)

/tmp/ipykernel_136/1597679837.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({

Encode Severity Column

In [13]:
df.rename(columns={
    "Rate the severity of the stray dog issue in your area": "severity"
}, inplace=True)

In [16]:
df.columns = df.columns.str.strip()

In [17]:
print(df.columns)

Index(['Username', '1. Your Name', '2. Contact Number (Optional)',
       '3. Area / Locality Name', '4. Your Pin code',
       '5. Approximate number of stray dogs you see daily in your area',
       '6. Among the stray dogs you observe in your area, what is the approximate male-to-female ratio?',
       '7. Have you noticed an increase in stray dog population over the past year?',
       '8. Time when you see most stray dogs:',
       '9. Approximate number of puppy litters you've observed in the past 6 months:',
       '10.  What typically happens to puppies in your area? (Select all that apply)',
       '11. Common behavior of strays in your area:',
       '12. Do dogs form packs in your area?',
       '13. Have you or anyone you know been bitten/chased by a stray dog?',
       '14. If yes, when did the last incident occur?',
       '15. Are there food outlets/restaurants nearby that attract dogs?',
       '16. Are there open garbage dumps in your area?',
       '17. Presence of water sources:', '18. Do residents feed stray dogs?',
       '19. Are there animal welfare volunteers/NGOs active in your area? (if yes then provide us with information)',
       '20. Have you seen sterilized dogs (ear-notched)?',
       '21.  Have you seen any injured dog in the past 6 months?',
       '22. Rate the severity of the stray dog issue in your area:',
       '23. Main concerns (select all that apply):',
       '24. Has this issue affected your quality of life?',
       '25. Any recommendations to solve this problem:'],
      dtype='object')

In [18]:
df.rename(columns={
    '22. Rate the severity of the stray dog issue in your area:': 'severity'
}, inplace=True)

In [19]:
df.rename(columns={
    '22. Rate the severity of the stray dog issue in your area:': 'severity'
}, inplace=True)

In [20]:
df[["severity"]].head()

   severity
0       1.0
1       3.0
2       3.0
3       4.0
4       2.0

Remove Duplicate Rows

In [21]:
df = df.drop_duplicates()

Convert Columns to Numeric

In [22]:
df = df.apply(pd.to_numeric, errors="ignore")

/tmp/ipykernel_136/3400095637.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")

In [ ]:
Save Cleaned Dataset

In [23]:
df.to_csv("cleaned_stray_dog_data.csv", index=False)